"""Small, genuinely-trained supervised ML model: "days until this household
needs a water/sewage delivery."

--------------------------------------------------------------------------
HONESTY NOTE — read this before trusting anything this file predicts:

The physics-based model already in common.py (chlorine-decay kinetics +
tank-depletion arithmetic in `depletion_days_band` / `predicted_needs_truck`)
is a CLOSED-FORM, DETERMINISTIC function of a household's inputs (tank size,
household size, consumption rate, sewage fill rate, hours since last
delivery, temperature). There is no real-world sensor data for this project
(no such household-level metering data exists publicly for Nunavik) — so the
only "ground truth" labels available to train a supervised model on are
generated BY RUNNING THAT SAME FORMULA on many sampled households.

That means this model is, by construction, learning to *approximate a
formula we already have in exact closed form*. It cannot discover any signal,
pattern, or relationship the physics model doesn't already encode, because
there is no noise, no unmeasured confounder, and no unmodeled real-world
effect in the training data for it to find. A near-perfect R² here is
EXPECTED and is not evidence of the model "learning something new" — it is
evidence that gradient-boosted trees are good at curve-fitting a smooth,
low-dimensional deterministic function.

What this file DOES honestly demonstrate: a real, working supervised-ML
training pipeline (sampling -> features -> train/test split -> fit -> holdout
evaluation) that a team could point real sensor telemetry at later, if/when
such data existed, to potentially learn corrections the physics model misses
(e.g. household behavioral drift, sensor drift, seasonal effects not in the
Q10 model). Today, with only simulated data, it is a methodology proof, not
a claim of superior predictive power over common.py's physics model.
--------------------------------------------------------------------------
"""

from __future__ import annotations

import json
import os
import pickle
import random
from datetime import datetime, timedelta

import numpy as np

from common import (
    Household,
    PER_CAPITA_LOW_LPD,
    PER_CAPITA_HIGH_LPD,
    TANK_SIZES_L,
    FREEZE_DRIP_THRESHOLD_C,
    depletion_days_band,
)

MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ml_predictor_model.pkl")

FEATURE_NAMES = [
    "household_size",
    "tank_capacity_l",
    "consumption_lpd",
    "temp_c",
    "hours_since_delivery",
    "sewage_fill_rate_pct_per_day",
    "sewage_baseline_pct",
]

try:
    from sklearn.ensemble import GradientBoostingRegressor
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import r2_score, mean_absolute_error
    _HAS_SKLEARN = True
except ImportError:
    _HAS_SKLEARN = False


def _sample_household(rng: random.Random, now: datetime) -> tuple[dict, Household]:
    """Draw one synthetic household using the SAME realistic ranges already
    established in common.py (per-capita consumption band, tank sizes,
    sewage-fill-rate-relative-to-consumption relationship) so the synthetic
    distribution matches the app's own demo fleet rather than an arbitrary
    made-up range."""
    household_size = rng.randint(1, 8)
    tank_capacity_l = rng.choice(TANK_SIZES_L)
    per_capita = rng.uniform(PER_CAPITA_LOW_LPD, PER_CAPITA_HIGH_LPD)
    consumption_lpd = per_capita * household_size
    hours_since_delivery = rng.uniform(0, 160)
    sewage_baseline_pct = rng.uniform(5, 95)
    sewage_fill_rate_pct_per_day = (consumption_lpd / tank_capacity_l) * 100.0 * rng.uniform(1.0, 1.3)
    # Wide temp range incl. below the freeze-drip threshold so that branch of
    # the physics model is represented in training data too.
    temp_c = rng.uniform(-40.0, 15.0)

    h = Household(
        id="SYNTH",
        community="synthetic",
        household_size=household_size,
        tank_capacity_l=tank_capacity_l,
        last_delivery=now - timedelta(hours=hours_since_delivery),
        initial_chlorine_mgL=rng.uniform(1.3, 1.8),
        has_auto_sensor=True,
        consumption_lpd=consumption_lpd,
        sewage_fill_rate_pct_per_day=sewage_fill_rate_pct_per_day,
        sewage_baseline_pct=sewage_baseline_pct,
        record_start=now - timedelta(hours=hours_since_delivery),
    )
    features = {
        "household_size": household_size,
        "tank_capacity_l": tank_capacity_l,
        "consumption_lpd": consumption_lpd,
        "temp_c": temp_c,
        "hours_since_delivery": hours_since_delivery,
        "sewage_fill_rate_pct_per_day": sewage_fill_rate_pct_per_day,
        "sewage_baseline_pct": sewage_baseline_pct,
    }
    return features, h


def generate_dataset(n: int = 4000, seed: int = 42) -> tuple[np.ndarray, np.ndarray]:
    """Build (X, y) where y = the "soonest" days-until-service-needed band
    from the EXISTING physics function `depletion_days_band` (water side) —
    i.e. the label is not invented, it's computed by importing and calling
    the exact same math already in production in common.py."""
    rng = random.Random(seed)
    now = datetime.now()
    X = np.zeros((n, len(FEATURE_NAMES)), dtype=float)
    y = np.zeros(n, dtype=float)
    for i in range(n):
        feats, h = _sample_household(rng, now)
        soonest_days, _latest_days = depletion_days_band(h, feats["temp_c"], now)
        X[i, :] = [feats[k] for k in FEATURE_NAMES]
        y[i] = soonest_days
    return X, y


def train_and_evaluate(n: int = 4000, seed: int = 42) -> dict:
    """Train on synthetic data, evaluate on a held-out split, and persist the
    fitted model (or its coefficients, in the numpy fallback) to disk.
    Returns a dict of honest fit-quality metrics for reporting."""
    X, y = generate_dataset(n=n, seed=seed)

    if _HAS_SKLEARN:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=seed)
        model = GradientBoostingRegressor(
            n_estimators=120, max_depth=3, learning_rate=0.1, random_state=seed
        )
        model.fit(X_train, y_train)
        preds = model.predict(X_test)
        r2 = r2_score(y_test, preds)
        mae = mean_absolute_error(y_test, preds)
        with open(MODEL_PATH, "wb") as f:
            pickle.dump({"backend": "sklearn", "model": model, "features": FEATURE_NAMES}, f)
        metrics = {
            "backend": "sklearn.GradientBoostingRegressor",
            "n_train": len(X_train),
            "n_test": len(X_test),
            "r2": float(r2),
            "mae_days": float(mae),
        }
    else:
        # Dependency-free fallback: plain least-squares linear regression
        # (numpy.linalg.lstsq) on the raw features plus a bias column. The
        # true relationship (tank depletion) is close to linear in most of
        # these features, so even this simple fallback should fit fairly
        # well — but it is a strictly weaker approximator than a tree
        # ensemble and won't capture the freeze-multiplier kink as cleanly.
        n_test = int(0.25 * len(X))
        idx = np.arange(len(X))
        rs = np.random.RandomState(seed)
        rs.shuffle(idx)
        test_idx, train_idx = idx[:n_test], idx[n_test:]
        X_train, X_test = X[train_idx], X[test_idx]
        y_train, y_test = y[train_idx], y[test_idx]

        A_train = np.hstack([X_train, np.ones((len(X_train), 1))])
        coef, *_ = np.linalg.lstsq(A_train, y_train, rcond=None)

        A_test = np.hstack([X_test, np.ones((len(X_test), 1))])
        preds = A_test @ coef

        ss_res = float(np.sum((y_test - preds) ** 2))
        ss_tot = float(np.sum((y_test - np.mean(y_test)) ** 2))
        r2 = 1 - ss_res / ss_tot if ss_tot > 0 else float("nan")
        mae = float(np.mean(np.abs(y_test - preds)))

        with open(MODEL_PATH, "wb") as f:
            pickle.dump({"backend": "numpy_lstsq", "coef": coef, "features": FEATURE_NAMES}, f)
        metrics = {
            "backend": "numpy.linalg.lstsq (sklearn unavailable fallback)",
            "n_train": len(X_train),
            "n_test": len(X_test),
            "r2": float(r2),
            "mae_days": mae,
        }
    return metrics


def _load_model() -> dict:
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


def predict_days_until_service(household: "Household", temp_c: float, now: datetime) -> float:
    """Load the persisted model (training it first if the pickle is missing)
    and predict days-until-service for one live Household object from the
    app. Mirrors the same feature set used at training time."""
    if not os.path.exists(MODEL_PATH):
        train_and_evaluate()
    bundle = _load_model()
    hours_since_delivery = max((now - household.last_delivery).total_seconds() / 3600.0, 0.0)
    x = np.array([[
        household.household_size,
        household.tank_capacity_l,
        household.consumption_lpd,
        temp_c,
        hours_since_delivery,
        household.sewage_fill_rate_pct_per_day,
        household.sewage_baseline_pct,
    ]], dtype=float)

    if bundle["backend"] == "sklearn":
        pred = bundle["model"].predict(x)[0]
    else:
        x_bias = np.hstack([x, np.ones((1, 1))])
        pred = float(x_bias @ bundle["coef"])
    return max(0.0, float(pred))


if __name__ == "__main__":
    metrics = train_and_evaluate()
    print(json.dumps(metrics, indent=2))
    print()
    print("HONEST TAKEAWAY: this model is trained on labels computed by the SAME")
    print("deterministic physics formula already in common.py (depletion_days_band).")
    print("A near-1.0 R2 / small MAE means the model successfully re-derived a known")
    print("closed-form formula from samples of it — NOT that it discovered new")
    print("real-world signal. There is no noise or unmeasured confounder in this")
    print("synthetic dataset for it to find. See the module docstring for full context.")
